### ISSUE TITLE
160

### ISSUE THREAD

**Issue by ALexus003** [XopMC/C-Sharp-Mnemonic#1]
Нужно для Mnemo-XopMC.exe использовать адрес ХЕШ160 ?

**Comment by XopMC** [comment]
> Нужно для Mnemo-XopMC.exe использовать адрес ХЕШ160 ?

Нет, только адреса

**Comment by ALexus003** [comment]
она работает на CPU ? что-то скорость у меня Speed: 677 Keys/s

**Comment by ALexus003** [comment]
> > Нужно ли для Mnemo-XopMC.exe использовать адрес ХЕШ160 ?
> 
> Нет, только адрес
она работает на процессоре? что-то у меня Скорость: 677 Keys/s
и я правильно понимаю, что она находит сид фразу и подбирает к адресу, и если предполагается и есть она вообще в этом адресе тогда и выводит?

**Comment by ALexus003** [comment]
???

**Comment by XopMC** [comment]
> > > Нужно ли для Mnemo-XopMC.exe использовать адрес ХЕШ160 ?
> > 
> > 
> > Нет, только адрес
> > она работает на процессоре? что-то у меня Скорость: 677 Keys/s
> > и я правильно понимаю, что она находит сид фразу и подбирает к адресу, и если предполагается и есть она вообще в этом адресе тогда и выводит?

Не понял вопроса.
Программа генерирует псевдослучайную мнемонику, **вычисляет** по ней адрес и сверяется с базой, есть ли данный адрес там

**Comment by ALexus003** [comment]
> > > > Нужно ли для Mnemo-XopMC.exe использовать адрес ХЕШ160 ?
> > > 
> > > 
> > > Нет, только адрес 
> > > она работает на процессоре? что-то у меня скорость: 677 Keys/s 
> > > и я правильно понимаю, что она находит сиду фразу и подбирает адрес, и если учитывает и есть она вообще в этом адресе тогда и выводит?
> 
> Не понял вопрос. Программа вычисляет псевдослучайную мнемонику, **вычисляет** по ней адрес и сверяется с базой, есть ли указанный адрес там

с какой базой? где эта база ? сама папка 6мб весит , с чем она сверяет? онлайн адрес в интернете? я значит должен быть онлайн ?

**Comment by XopMC** [comment]
> > > > > Нужно ли для Mnemo-XopMC.exe использовать адрес ХЕШ160 ?
> > > > 
> > > > 
> > > > Нет, только адрес
> > > > она работает на процессоре? что-то у меня скорость: 677 Keys/s
> > > > и я правильно понимаю, что она находит сиду фразу и подбирает адрес, и если учитывает и есть она вообще в этом адресе тогда и выводит?
> > 
> > 
> > Не понял вопрос. Программа вычисляет псевдослучайную мнемонику, **вычисляет** по ней адрес и сверяется с базой, есть ли указанный адрес там
> 
> с какой базой? где эта база ? сама папка 6мб весит , с чем она сверяет? онлайн адрес в интернете? я значит должен быть онлайн ?

Читайте описание!

База адресов, на которых есть баланс

**Comment by XopMC** [comment]
> > > > > Нужно ли для Mnemo-XopMC.exe использовать адрес ХЕШ160 ?
> > > > 
> > > > 
> > > > Нет, только адрес
> > > > она работает на процессоре? что-то у меня скорость: 677 Keys/s
> > > > и я правильно понимаю, что она находит сиду фразу и подбирает адрес, и если учитывает и есть она вообще в этом адресе тогда и выводит?
> > 
> > 
> > Не понял вопрос. Программа вычисляет псевдослучайную мнемонику, **вычисляет** по ней адрес и сверяется с базой, есть ли указанный адрес там
> 
> с какой базой? где эта база ? сама папка 6мб весит , с чем она сверяет? онлайн адрес в интернете? я значит должен быть онлайн ?

Взять можно, например тут -http://addresses.loyce.club

А базы эфира ищите сами.

**Comment by ALexus003** [comment]
> > > > > > Нужно ли для Mnemo-XopMC.exe использовать адрес ХЕШ160 ?
> > > > > 
> > > > > 
> > > > > Нет, только адрес 
> > > > > она работает на процессоре? что-то у меня скорость: 677 Keys/s 
> > > > > и я правильно понимаю, что она находит сиду фразу и подбирает адрес, и если посещает и есть она вообще в этом адресе тогда и выводит?
> > > 
> > > 
> > > Не понял вопрос. Программа вычисляет псевдослучайную мнемонику, **вычисляет** по ней адрес и сверяется с базой, есть указанный адрес там
> > 
> > 
> > с какой базой? где эта база ? сама папка 6мб весит , с чем она сверяет? онлайн адрес в интернете? я значит должен быть онлайн ?
> 
> Взять можно, например тут - http://addresses.loyce.club
> 
> А базу эфира ищите сами.
мне не нужна база ,у меня есть адреса . Как она сверяется с чем ? откуда берет сверку ? как называется файл? и еще я спрашивал за онлайн? я задаю несколько вопросов а не один!

**Comment by ALexus003** [comment]
> > > > > > > Нужно ли для Mnemo-XopMC.exe использовать адрес ХЕШ160 ?
> > > > > > 
> > > > > > 
> > > > > > Нет, только адрес 
> > > > > > она работает на процессоре? что-то у меня скорость: 677 Keys/s 
> > > > > > и я правильно понимаю, что она находит сидусу фразу и подбирает адрес, и если посещает и есть она вообще в этом адресе тогда и выводит?
> > > > 
> > > > 
> > > > Не понял вопрос. Программа вычисляет псевдослучайную мнемонику, **вычисляет** по ней адрес и сверяется с базой, есть указанный адрес там
> > > 
> > > 
> > > с какой базой? где эта база ? сама папка 6мб весит , с чем она сверяет? онлайн адрес в интернете? я значит должен быть онлайн ?
> > 
> > 
> > Взять можно, например тут - http://addresses.loyce.club
> > А базу эфира ищите сами. 
> > мне не нужна база ,у меня есть адрес . Как она сверяется с чем ? откуда берет сверку ? как называется файл? и еще я спрашивал за онлайн? я задаю несколько вопросов не один!

или по ссылке и есть файл с которыми она должна сверять ? куда мне его вставить ? получается я прогоняю в холостую сейчас адреса свои ?

**Comment by XopMC** [comment]
> > > > > > > Нужно ли для Mnemo-XopMC.exe использовать адрес ХЕШ160 ?
> > > > > > 
> > > > > > 
> > > > > > Нет, только адрес
> > > > > > она работает на процессоре? что-то у меня скорость: 677 Keys/s
> > > > > > и я правильно понимаю, что она находит сиду фразу и подбирает адрес, и если посещает и есть она вообще в этом адресе тогда и выводит?
> > > > 
> > > > 
> > > > Не понял вопрос. Программа вычисляет псевдослучайную мнемонику, **вычисляет** по ней адрес и сверяется с базой, есть указанный адрес там
> > > 
> > > 
> > > с какой базой? где эта база ? сама папка 6мб весит , с чем она сверяет? онлайн адрес в интернете? я значит должен быть онлайн ?
> > 
> > 
> > Взять можно, например тут - http://addresses.loyce.club
> > А базу эфира ищите сами.
> > мне не нужна база ,у меня есть адреса . Как она сверяется с чем ? откуда берет сверку ? как называется файл? и еще я спрашивал за онлайн? я задаю несколько вопросов а не один!


Повторюсь, **Читайте описание!**

Там указано, как и куда прикрепить базу.

О каком онлайне идёт речь, если сверка идёт с базой?

"Как она сверяется с чем ? откуда берет сверку ?" - вопросы ни о чем, учите матчасть. (ответ давал ещё во втором сообщении - Программа генерирует псевдослучайную мнемонику, вычисляет по ней адрес и сверяется с базой, есть ли данный адрес там)

**Comment by ALexus003** [comment]
> > > > > > > > Нужно ли для Mnemo-XopMC.exe использовать адрес ХЕШ160 ?
> > > > > > > 
> > > > > > > 
> > > > > > > Нет, только адрес 
> > > > > > > она работает на процессоре? что-то у меня скорость: 677 Keys/s 
> > > > > > > и я правильно понимаю, что она находит сидусу фразу и подбирает адрес, и если посещает и есть она вообще в этом адресе тогда и выводит?
> > > > > 
> > > > > 
> > > > > Не понял вопрос. Программа вычисляет псевдослучайную мнемонику, **вычисляет** по ней адрес и сверяется с базой, есть указанный адрес там
> > > > 
> > > > 
> > > > с какой базой? где эта база ? сама папка 6мб весит , с чем она сверяет? онлайн адрес в интернете? я значит должен быть онлайн ?
> > > 
> > > 
> > > Взять можно, например тут - http://addresses.loyce.club 
> > > А базу эфира ищите сами. 
> > > мне не нужна база ,у меня есть адрес . Как она сверяется с чем ? откуда берет сверку ? как называется файл? и еще я спрашивал за онлайн? я задаю несколько вопросов не один!
> 
> Повторюсь, **Читайте описание!**
> 
> Там указано, как и куда прикрепить базу.
> 
> О каком онлайне идёт речь, если сверка идёт с базой?
> 
> "Как она сверяется с чем ? откуда берет сверку ?" - вопросы ни о чем, учите матчасть. (ответ давал ещёслучай во втором - Программа использует псевдочайную мнемонику, вычисляет по ней адрес и сверяется с базой, есть ли адрес там)

вы меня не поняли ,допустим у меня есть адрес от которого я забыл сид фразу ,дальше я создаю файл с этим адресом bit.txt перетягиваю в приложение . вот как она и где будет сверять и генирировать этот адрес?

**Comment by XopMC** [comment]
> 

Да, но шансы на то, что подберет к 1 адресу - крайне низкие (1 к 2^256)

Поскольку тут идёт рандомная генерация мнемоники, рекомендую использовать базу адресов с балансом (ссылку на которую кидал выше) 

Чем больше база, тем больше шансов на попадание хоть в один (около 45000000 к 2^256)

подбора к 1 адресу не сущестует, это в любом случае будет рандомная генерация всяких адресов, пока не найдёт совпадение


Данный инструмент не подойдёт для восстановления забытой мнемоники, в случае если известны несколько слов, то лучше использовать другие инструменты.

Это же инструмент "на удачу" вдруг попадёт, ну либо для генерации адресов для личных нужд

**Comment by ALexus003** [comment]
я понял,спасибо большое!

**Comment by ALexus003** [comment]
Извиняюсь еще один вопрос , можете посоветовать прогу на прогон одного адреса мнемоники ?

**Comment by XopMC** [comment]
> Извиняюсь еще один вопрос , можете посоветовать прогу на прогон одного адреса мнемоники ?

https://github.com/gurnec/btcrecover
