### ISSUE TITLE
please add electrum old path m/0/0 

### ISSUE THREAD

**Issue by sokary2004** [XopMC/C-Sharp-Mnemonic#5]
please add electrum old path m/0/0 

i try to change word list for electrum but is not working .... 

electrum old wordlist + this path m/0/0   it is very usefully

**Comment by sokary2004** [comment]
https://brainwalletx.github.io/#chains

this link maybe useful

**Comment by XopMC** [comment]
Salut!
Thx for your feedback!
I'll try to add ElectrumOLD mnemonic in future updates

(do not try to change wordlist... Because ElectrumOLD Mnemonic have a different working principle )

You can use m/0/0 with parameter
'-P 0'
